name: Publish Package

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to publish (e.g. 1.0.0)"
        required: true
        type: string

permissions:
  contents: write
  packages: write

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Debug npm auth
        run: npm whoami
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Validate version
        run: |
          PACKAGE_VERSION=$(grep '"version":' package.json | cut -d'"' -f4)
          GIT_TAG=${GITHUB_REF#refs/tags/v}
          if [ "$GITHUB_EVENT_NAME" = "workflow_dispatch" ]; then
            GIT_TAG=${{ inputs.version }}
            if ! [[ $GIT_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
              echo "Error: Version must be in format x.y.z"
              exit 1
            fi
          fi

          if [ "$PACKAGE_VERSION" != "$GIT_TAG" ]; then
            echo "Error: Git tag version ($GIT_TAG) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Validate changelog
        run: |
          PACKAGE_VERSION=$(grep '"version":' package.json | cut -d'"' -f4)
          if ! grep -q "#### $PACKAGE_VERSION" CHANGELOG.md; then
            echo "Error: CHANGELOG.md does not contain an entry for version $PACKAGE_VERSION"
            exit 1
          fi

  publish:
    needs: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && inputs.version || github.ref_name }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
