name: Publish Package

on:
  push:
    tags:
      - "v*"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Validate version
        run: |
          PACKAGE_VERSION=$(node -p "require('./package.json').version")
          GIT_TAG=${GITHUB_REF#refs/tags/v}

          if [ "$PACKAGE_VERSION" != "$GIT_TAG" ]; then
            echo "Error: Git tag version ($GIT_TAG) does not match package.json version ($PACKAGE_VERSION)"
            exit 1
          fi

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
